# Generated by Django 3.1.3 on 2022-06-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20220608_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='happy',
            field=models.IntegerField(default=0),
        ),
    ]
