# Generated by Django 3.1.3 on 2022-06-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_question_happy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='happy',
        ),
    ]
